//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParentForm.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Child
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ClassId { get; set; }
        public string Gender { get; set; }
        public string School { get; set; }
        public string Age { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Parent Parent { get; set; }
    }
}
